services:
  metabase:
    image: metabase/metabase:v0.55.2.1
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - $METABASE_PORT:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: $METABASE_POSTGRES_DB
      MB_DB_PORT: 5432
      MB_DB_USER: $METABASE_POSTGRES_USER
      MB_DB_PASS: $METABASE_POSTGRES_PASSWORD
      MB_DB_HOST: $POSTGRES_HOST_DOCKER
    networks:
      - pokenet
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:latest
    container_name: postgres-pokemon
    hostname: $POSTGRES_HOST_DOCKER
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      METABASE_POSTGRES_USER: $METABASE_POSTGRES_USER
      METABASE_POSTGRES_DB: $METABASE_POSTGRES_DB
      METABASE_POSTGRES_PASSWORD: $METABASE_POSTGRES_PASSWORD
      DAGSTER_POSTGRES_USER: $DAGSTER_POSTGRES_USER
      DAGSTER_POSTGRES_PASSWORD: $DAGSTER_POSTGRES_PASSWORD
      DAGSTER_POSTGRES_DB: $DAGSTER_POSTGRES_DB
    networks:
      - pokenet
networks:
  pokenet:
    driver: bridge
